import type { paths as OpenApiPaths } from '../../types/api.generated';

export type OpenApiPath = keyof OpenApiPaths;

export const ADMIN_API_PATHS = {
    csrf: '/api/auth/csrf',
    adminAuthLogin: '/api/admin-auth/login',
    adminAuthLogout: '/api/admin-auth/logout',
    adminAuthStepUp: '/api/admin-auth/step-up',
    adminAuthMe: '/api/admin-auth/me',
    adminAuthPermissions: '/api/admin-auth/permissions',
    adminDashboard: '/api/admin/dashboard',
    analyticsOverview: '/api/analytics/overview',
    adminAnnouncements: '/api/admin/announcements',
    adminApprovals: '/api/admin/approvals',
    adminReviewPreview: '/api/admin/review/preview',
    adminAnnouncementBulkPreview: '/api/admin/announcements/bulk/preview',
    adminAnnouncementBulkApprove: '/api/admin/announcements/bulk-approve',
    adminAnnouncementBulkReject: '/api/admin/announcements/bulk-reject',
    adminAnnouncementBulk: '/api/admin/announcements/bulk',
    adminSessions: '/api/admin/sessions',
    adminTerminateSession: '/api/admin-auth/sessions/terminate',
    adminTerminateOtherSessions: '/api/admin-auth/sessions/terminate-others',
    adminAuditLog: '/api/admin/audit-log',
    adminAuditIntegrity: '/api/admin/audit-log/integrity',
    adminSecurityLog: '/api/admin/security',
    supportErrorReports: '/api/support/error-reports',
    communityFlags: '/api/community/flags',
    communityForums: '/api/community/forums',
    communityQa: '/api/community/qa',
    communityGroups: '/api/community/groups',
    homepageSections: '/api/admin/homepage/sections',
    adminLinks: '/api/admin/links',
    adminLinkCheck: '/api/admin/links/check',
    adminLinkHealthSummary: '/api/admin/links/health/summary',
    adminLinkReplace: '/api/admin/links/replace',
    adminMedia: '/api/admin/media',
    adminTemplates: '/api/admin/templates',
    adminAlerts: '/api/admin/alerts',
    adminUsers: '/api/admin/users',
    adminReports: '/api/admin/reports',
} as const satisfies Record<string, OpenApiPath>;
