/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/announcements/v3/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcement cards */
        get: {
            parameters: {
                query?: {
                    type?: components["schemas"]["ContentType"];
                    category?: string;
                    search?: string;
                    organization?: string;
                    location?: string;
                    qualification?: string;
                    salaryMin?: number;
                    salaryMax?: number;
                    sort?: "newest" | "oldest" | "deadline" | "views";
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Announcement cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnouncementCardListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcements */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Announcements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnouncementListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get announcement by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Announcement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnouncementResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Auth response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Auth response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookmarks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookmarks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnouncementListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Add bookmark */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookmarkCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookmark ids */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookmark ids */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookmarkIdsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove bookmark */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubscriptionRequest"];
                };
            };
            responses: {
                /** @description Subscription response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify subscription */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verify response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unsubscribe */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unsubscribe response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        /** Update profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileUpdateRequest"];
                };
            };
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile options */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Options */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileOptionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile recommendations */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recommendations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/forums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List forum posts */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forum posts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityForumListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create forum post */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityForumCreateRequest"];
                };
            };
            responses: {
                /** @description Forum post */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityForumResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/forums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete forum post */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Q&A threads */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Q&A threads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityQaListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create Q&A thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityQaCreateRequest"];
                };
            };
            responses: {
                /** @description Q&A thread */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityQaResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/qa/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Q&A thread */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/qa/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Answer Q&A thread */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityQaAnswerRequest"];
                };
            };
            responses: {
                /** @description Q&A thread */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityQaResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/community/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List study groups */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Study groups */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityGroupListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create study group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityGroupCreateRequest"];
                };
            };
            responses: {
                /** @description Study group */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityGroupResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete study group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List community flags */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    status?: components["schemas"]["CommunityFlagStatus"];
                    entityType?: components["schemas"]["CommunityEntityType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flags */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityFlagListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Report abusive content */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityFlagCreateRequest"];
                };
            };
            responses: {
                /** @description Flag */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityFlagResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/flags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Resolve flag */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/error-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a client error */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ErrorReportRequest"];
                };
            };
            responses: {
                /** @description Report received */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorReportResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/error-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List error reports */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    status?: components["schemas"]["ErrorReportStatus"];
                    errorId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Error reports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorReportListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/error-reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update error report */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ErrorReportUpdateRequest"];
                };
            };
            responses: {
                /** @description Error report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorReportResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ContentType: "job" | "result" | "admit-card" | "syllabus" | "answer-key" | "admission";
        AnnouncementCard: {
            id: string;
            title: string;
            slug: string;
            type: components["schemas"]["ContentType"];
            category: string;
            organization: string;
            location?: string | null;
            minQualification?: string | null;
            ageLimit?: string | null;
            salaryMin?: number | null;
            salaryMax?: number | null;
            /** @enum {string|null} */
            difficulty?: "easy" | "medium" | "hard" | null;
            cutoffMarks?: string | null;
            /** Format: date-time */
            deadline?: string | null;
            totalPosts?: number | null;
            /** Format: date-time */
            postedAt: string;
            viewCount: number;
            isActive: boolean;
        };
        Tag: {
            id: string;
            name: string;
            slug: string;
        };
        ImportantDate: {
            eventName: string;
            eventDate: string;
            description?: string;
        };
        Announcement: {
            id: string;
            title: string;
            slug: string;
            type: components["schemas"]["ContentType"];
            category: string;
            organization: string;
            content?: string;
            externalLink?: string;
            location?: string;
            /** Format: date-time */
            deadline?: string;
            minQualification?: string;
            ageLimit?: string;
            applicationFee?: string;
            salaryMin?: number;
            salaryMax?: number;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            cutoffMarks?: string;
            totalPosts?: number;
            /** Format: date-time */
            postedAt: string;
            /** Format: date-time */
            updatedAt?: string;
            isActive: boolean;
            viewCount: number;
            tags?: components["schemas"]["Tag"][];
            importantDates?: components["schemas"]["ImportantDate"][];
            jobDetails?: {
                [key: string]: unknown;
            };
        };
        AnnouncementResponse: {
            data: components["schemas"]["Announcement"];
        };
        AnnouncementListResponse: {
            data: components["schemas"]["Announcement"][];
            count?: number;
        };
        AnnouncementCardListResponse: {
            data: components["schemas"]["AnnouncementCard"][];
            count?: number;
            nextCursor: string | null;
            hasMore: boolean;
        };
        User: {
            id: string;
            email: string;
            name: string;
            role: string;
            createdAt: string;
            updatedAt: string;
        };
        AuthResponse: {
            data: {
                user: components["schemas"]["User"];
                token: string;
            };
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        BookmarkCreateRequest: {
            announcementId: string;
        };
        BookmarkIdsResponse: {
            data: string[];
        };
        MessageResponse: {
            message: string;
        };
        SubscriptionRequest: {
            /** Format: email */
            email: string;
            categories?: string[];
            /** @enum {string} */
            frequency?: "instant" | "daily" | "weekly";
        };
        SubscriptionResponse: {
            data: {
                verified: boolean;
            };
            message?: string;
        };
        UserProfile: {
            id: string;
            userId: string;
            preferredCategories: string[];
            preferredQualifications: string[];
            preferredLocations: string[];
            preferredOrganizations: string[];
            ageGroup?: string | null;
            educationLevel?: string | null;
            experienceYears: number;
            emailNotifications: boolean;
            pushNotifications: boolean;
            notificationFrequency: string;
            profileComplete: boolean;
            onboardingCompleted: boolean;
        };
        ProfileResponse: {
            data: components["schemas"]["UserProfile"];
        };
        ProfileUpdateRequest: {
            preferredCategories?: string[];
            preferredQualifications?: string[];
            preferredLocations?: string[];
            preferredOrganizations?: string[];
            ageGroup?: string | null;
            educationLevel?: string | null;
            experienceYears?: number;
            emailNotifications?: boolean;
            pushNotifications?: boolean;
            notificationFrequency?: string;
            profileComplete?: boolean;
            onboardingCompleted?: boolean;
        };
        ProfileOptions: {
            categories: string[];
            qualifications: string[];
            ageGroups: string[];
            educationLevels: string[];
            notificationFrequencies: string[];
            locations: string[];
            organizations: string[];
        };
        ProfileOptionsResponse: {
            data: components["schemas"]["ProfileOptions"];
        };
        Recommendation: components["schemas"]["Announcement"] & {
            matchScore: number;
            matchReasons: {
                [key: string]: number;
            };
        };
        RecommendationListResponse: {
            data: components["schemas"]["Recommendation"][];
        };
        /** @enum {string} */
        CommunityEntityType: "forum" | "qa" | "group";
        /** @enum {string} */
        CommunityFlagStatus: "open" | "reviewed" | "resolved";
        CommunityForumPost: {
            id: string;
            title: string;
            content: string;
            category: string;
            author: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityQaThread: {
            id: string;
            question: string;
            answer?: string | null;
            answeredBy?: string | null;
            author: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityStudyGroup: {
            id: string;
            name: string;
            topic: string;
            language: string;
            link?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityFlag: {
            id: string;
            entityType: components["schemas"]["CommunityEntityType"];
            entityId: string;
            reason: string;
            reporter?: string | null;
            status: components["schemas"]["CommunityFlagStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityForumCreateRequest: {
            title: string;
            content: string;
            category: string;
            author?: string;
        };
        CommunityQaCreateRequest: {
            question: string;
            author?: string;
        };
        CommunityQaAnswerRequest: {
            answer: string;
            answeredBy?: string;
        };
        CommunityGroupCreateRequest: {
            name: string;
            topic: string;
            language: string;
            link?: string;
        };
        CommunityFlagCreateRequest: {
            entityType: components["schemas"]["CommunityEntityType"];
            entityId: string;
            reason: string;
            reporter?: string;
        };
        CommunityForumResponse: {
            data: components["schemas"]["CommunityForumPost"];
        };
        CommunityQaResponse: {
            data: components["schemas"]["CommunityQaThread"];
        };
        CommunityGroupResponse: {
            data: components["schemas"]["CommunityStudyGroup"];
        };
        CommunityFlagResponse: {
            data: components["schemas"]["CommunityFlag"];
        };
        CommunityForumListResponse: {
            data: components["schemas"]["CommunityForumPost"][];
            count?: number;
        };
        CommunityQaListResponse: {
            data: components["schemas"]["CommunityQaThread"][];
            count?: number;
        };
        CommunityGroupListResponse: {
            data: components["schemas"]["CommunityStudyGroup"][];
            count?: number;
        };
        CommunityFlagListResponse: {
            data: components["schemas"]["CommunityFlag"][];
            count?: number;
        };
        ErrorReportRequest: {
            errorId: string;
            message: string;
            pageUrl?: string;
            userAgent?: string;
            note?: string;
            stack?: string;
            componentStack?: string;
            timestamp?: string;
        };
        ErrorReportResponse: {
            data: components["schemas"]["ErrorReport"];
        };
        /** @enum {string} */
        ErrorReportStatus: "new" | "triaged" | "resolved";
        ErrorReport: {
            id: string;
            errorId: string;
            message: string;
            pageUrl?: string | null;
            userAgent?: string | null;
            note?: string | null;
            adminNote?: string | null;
            stack?: string | null;
            componentStack?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
            status: components["schemas"]["ErrorReportStatus"];
            userId?: string | null;
            userEmail?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            resolvedBy?: string | null;
        };
        ErrorReportListResponse: {
            data: components["schemas"]["ErrorReport"][];
            count?: number;
        };
        ErrorReportUpdateRequest: {
            status: components["schemas"]["ErrorReportStatus"];
            adminNote?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
